# Generated by Django 5.1.4 on 2024-12-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_conversation_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
