# Generated by Django 5.1.4 on 2024-12-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_alter_conversation_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
