# Generated by Django 5.1.4 on 2024-12-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Desciption',
            new_name='description',
        ),
    ]
